wandb_version: 1

activation:
  value: ReLU
base_lr:
  value: 1.7638074314693687e-05
batch_norm:
  value: 2
batch_size:
  value: 435
conv_pru_bound:
  value: 0.06505760488720713
data_bn:
  value: 1
dataset:
  value: cifar10
down_ratio:
  value: 0.09155483231379208
fc_pru_bound:
  value: 0.11465899365510894
fine_tune:
  value: 40
lr:
  value: 0.05831809827988267
lr_scheduler:
  value: cyclic
method:
  value: Hard
model_dir:
  value: /storage/hpc/52/jiangz9/Experiments/TPAMI/cifar10/vgg16/prune
model_type:
  value: mini
momentum:
  value: 0.9673702781941942
name:
  value: hard_0.01_0.1_15
net:
  value: vgg16
npbar:
  value: 'false'
num_circles:
  value: 4
num_cls:
  value: 7
num_epoch:
  value: 78
num_step:
  value: -2
num_workers:
  value: 3
optimizer:
  value: SGD
project:
  value: prune
prune_every:
  value: 11
total_amount:
  value: 0.6467755954486887
train_mode:
  value: pru
up_ratio:
  value: 0.12179448750831154
val_epoch:
  value: 1
weight_decay:
  value: 0.000751460407196949
