phase_0:
  batch_size: 4
  crop_size: 128
  data_size: 160
  lr: 0.0
  lr_e: 0.01
  lr_scheduler: linear
  start_epoch: 0
  end_epoch: 1
phase_1:
  batch_size: 128
  crop_size: 128
  data_size: 160
  lr: 0.01
  lr_e: 0.1
  lr_scheduler: linear
  start_epoch: 1
  end_epoch: 2
phase_2:
  batch_size: 128
  crop_size: 160
  data_size: 128
  lr: 0.1
  lr_e: 0.01
  lr_scheduler: linear
  start_epoch: 2
  end_epoch: 8
phase_3:
  batch_size: 128
  crop_size: 128
  data_size: 160
  lr: 0.1
  lr_e: 0.01
  lr_scheduler: linear
  start_epoch: 10
  end_epoch: 15
