# phase_0:
#   batch_size: 128
#   crop_size: 128
#   data_size: 160
#   lr: 0.0
#   lr_e: 0.4
#   lr_scheduler: linear
#   start_epoch: 0
#   end_epoch: 1
phase_1:
  batch_size: 128
  crop_size: 128
  data_size: 160
  lr: 0.
  lr_e: 0.4
  lr_scheduler: linear
  start_epoch: 0
  end_epoch: 1
phase_2:
  batch_size: 128
  crop_size: 128
  data_size: 160
  lr: 0.4
  lr_e: 0.04
  lr_scheduler: linear
  start_epoch: 1
  end_epoch: 6
phase_3:
  batch_size: 64
  crop_size: 288
  data_size: 352
  lr: 0.04
  lr_e: 0.004
  lr_scheduler: linear
  start_epoch: 6
  end_epoch: 12
phase_4:
  batch_size: 64
  crop_size: 288
  data_size: 352
  lr: 0.004
  lr_e: 0.0004
  lr_scheduler: linear
  start_epoch: 12
  end_epoch: 15
