wandb_version: 1

conv_pru_bound:
  value: 0.14205048142987203
fc_pru_bound:
  value: 0.14905476933181583
model_dir:
  value: /storage/hpc/52/jiangz9/Experiments/TPAMI/cifar10/vgg16/prune
prune_every:
  value: 17
