activation: LeakyReLU
attack: noise
batch_norm: 1
batch_size: 128
config: null
conv_dn_rate: 0.95
crop_size: 128
cuda:
- 0
data_bn: 1
data_size: 160
dataset: imagenet
dir: ''
dn_rate: 0.9
eta_dn: 0
eta_fixed: 0
eta_float: 0
exp_id: noise_015
linear_dn_rate: 0.9
lip_inverse: 0
lip_layers: 2
lip_loss: 0.0
local_rank: 0
lr: 0.0
lr_e: 0.4
lr_scheduler: linear
mode: client
model_dir: imagenet/vgg16_noise_015
model_type: net
momentum: 0.9
net: vgg16
node_rank: 0
noise_eps: 0.06
noise_type: noise
num_cls: 1000
num_epoch: 1
num_workers: 1
optimizer: SGD
port: 52162
print_every: 100
prune_every: 30
record_lip: 1
resume: 0
save_name: warmup
sigma: 0.15
start_epoch: 0
train_mode: std
val_mode: std
warmup: 2
weight_decay: 0.0005
world_size: 4
yml_file: ./imagenet_cfg/p_0.yml
